--STAGE > LOAD RAW > PARSE > QUERY

CREATE SCHEMA YOUTUBE;

CREATE OR REPLACE STAGE YOUTUBE.YOUTUBE_STG
    URL = 's3://sf-lake/'
    STORAGE_INTEGRATION = AWS_S3_INT
;

LIST @YOUTUBE.YOUTUBE_STG;

CREATE FILE FORMAT YOUTUBE.JSON_FMT
    TYPE = JSON ;

CREATE TABLE STATISTICS_RAW (
    RAW_FILE VARIANT
);

COPY INTO SOCIAL_MEDIAS.YOUTUBE.STATISTICS_RAW
    FROM @SOCIAL_MEDIAS.YOUTUBE.YOUTUBE_STG
    file_format= SOCIAL_MEDIAS.YOUTUBE.JSON_FMT
    files = ('youtube_data.json');

SELECT * FROM SOCIAL_MEDIAS.YOUTUBE.STATISTICS_RAW;
