CREATE OR REPLACE FILE FORMAT JSON_FMT
    TYPE = JSON ;

DESC FILE FORMAT JSON_FMT;

COPY INTO OPEN_DATA.NOAA.MAGNETOMETERS_7_DAYS_RAW
    FROM @OPEN_DATA.NOAA.NOAA_STAGE/json/goes/primary/magnetometers-7-day.json
    FILE_FORMAT = JSON_FMT;
